# Generated by Django 5.0.6 on 2024-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_records_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='email',
            field=models.CharField(max_length=35),
        ),
    ]
